apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels: {app: backend}
  template:
    metadata:
      labels: {app: backend}
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: backend
          image: ghcr.io/mqharris/knight-club/backend:dev
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom: {secretKeyRef: {name: mysql-secrets, key: MYSQL_DATABASE}}
            - name: DB_USER
              valueFrom: {secretKeyRef: {name: mysql-secrets, key: MYSQL_USER}}
            - name: DB_PASSWORD
              valueFrom: {secretKeyRef: {name: mysql-secrets, key: MYSQL_PASSWORD}}
          readinessProbe:
            httpGet: {path: /healthz, port: 8080}
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: {path: /livez, port: 8080}
            initialDelaySeconds: 15
