apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels: {app: webui}
  template:
    metadata:
      labels: {app: webui}
    spec:
      containers:
        - name: webui
          image: ghcr.io/mqharris/knight-club/webui:dev
          ports:
            - containerPort: 80
