apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - webui/deployment.yaml
  - webui/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - mysql/statefulset.yaml
  - mysql/service.yaml
  - ingress.yaml

namespace: knight-club

configMapGenerator:
  - name: mysql-init-sql
    files:
      - mysql/initdb.sql

# secretGenerator:
#   - name: mysql-secrets
#     behavior: create
#     literals:
#       - MYSQL_ROOT_PASSWORD=password
#       - MYSQL_DATABASE=knightclub
#       - MYSQL_USER=app
#       - MYSQL_PASSWORD=password
generatorOptions:
  disableNameSuffixHash: true