apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: ghcr.io/mqharris/knight-club/webui
    newTag: dev
  - name: ghcr.io/mqharris/knight-club/backend
    newTag: dev

patches:
  - target: {kind: Deployment, name: webui}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target: {kind: Deployment, name: backend}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - path: patch-webui-svc-nodeport.yaml
